const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("study", {
  getState: () => ipcRenderer.invoke("app:get-state"),
  refreshAuth: () => ipcRenderer.invoke("auth:refresh"),
  signIn: () => ipcRenderer.invoke("auth:sign-in"),
  cancelSignIn: () => ipcRenderer.invoke("auth:cancel-sign-in"),
  signOut: () => ipcRenderer.invoke("auth:sign-out"),
  manageUsage: () => ipcRenderer.invoke("auth:manage-usage"),
  createCourse: (input) => ipcRenderer.invoke("course:create", input),
  selectCourse: (id) => ipcRenderer.invoke("course:select", id),
  updateCourse: (id, patch) => ipcRenderer.invoke("course:update", id, patch),
  deleteCourse: (id) => ipcRenderer.invoke("course:delete", id),
  startSession: () => ipcRenderer.invoke("session:start"),
  endSession: () => ipcRenderer.invoke("session:end"),
  updateSettings: (patch) => ipcRenderer.invoke("settings:update", patch),
  addMaterial: () => ipcRenderer.invoke("material:add"),
  updateMaterial: (courseId, materialId, patch) => ipcRenderer.invoke("material:update", courseId, materialId, patch),
  removeMaterial: (courseId, materialId) => ipcRenderer.invoke("material:remove", courseId, materialId),
  captureMac: () => ipcRenderer.invoke("frame:capture-mac"),
  askTutor: (question) => ipcRenderer.invoke("tutor:ask", question),
  cancelTutor: () => ipcRenderer.invoke("tutor:cancel"),
  stopVoice: () => ipcRenderer.invoke("voice:stop"),
  transcribe: (bytes) => ipcRenderer.invoke("voice:transcribe", bytes),
  onState: (callback) => ipcRenderer.on("app:state", (_event, value) => callback(value)),
  onFrame: (callback) => ipcRenderer.on("frame:update", (_event, value) => callback(value)),
  onReceiver: (callback) => ipcRenderer.on("receiver:update", (_event, value) => callback(value)),
  onTutorState: (callback) => ipcRenderer.on("tutor:state", (_event, value) => callback(value)),
  onVoiceState: (callback) => ipcRenderer.on("voice:state", (_event, value) => callback(value)),
  onVoiceError: (callback) => ipcRenderer.on("voice:error", (_event, value) => callback(value)),
  onAsrState: (callback) => ipcRenderer.on("asr:state", (_event, value) => callback(value)),
});
